## Training the classifier

Use this notebook to train the image3c classifier using the clusters assigned previously
as labels for classes.

Before running this notebook, the [imageprep.ipynb](imageprep.ipynb) notebook needs to be run
to put the images into the rigth format for training and to create a file with
class labels from the clustering results.

To perform the training we only need to import image3c.network_training.

This notebook creates a dictionary of parameters to tell the trainer where to
find images and labels, where to save the trained network, and other network
parameters.

In [1]:
from image3c import network_training

### Create the parameter dictionary

- description :   Description of the experiment
- num_classes :   The number of clusters found with Vortex clustering
- datafile :      The location of the datafile in numpy format (from [imageprep.ipynb](imageprep.ipynb))
- labelsfile :    The location of the file with label classes (from [imageprep.ipynb](imageprep.ipynb))
- CheckointDir :
- num_channels :  The number of channels in the dataset.
- channels :      A list of channels to be used for training, i.e., [0, 1, 2] or [1,2,4] if you want subset of channels.
- iterations :   How many iterations to perform. Around 25,000 seems to work well
- batchsize  :   How many images in an iteration. This depends on the memory of your system or GPU. Start with 256 and decrease it if you experience memory errrors.
- 

In [2]:
params = dict()
params['description'] = "norm_std" ## Description for your training
num_classes = 7            ## Number of class, typically the same as cluster found previously

params['datafile'] = 'Data/snail_images.npy'  # path to the numpy file of the image array
### where are the labels
params['labelsfile'] = 'Data/snail_labels.npy' # path to numpy file with cluster labels
params['CheckpointDir'] = "Checkpoints/test" # path to checkpoints
params['num_channels'] = 5
params['channels'] = [0,2,4] # what channels to use
params['combine'] = [[0,8], [4,7]] 

params['clusterlist'] = list(range(num_classes))


params['iterations'] = 25000 #25000
params['learning_rate'] = 0.001 #0.0006
params['droprate'] = 0.0
params['l2f'] = 0.006 #0.004
params['batchsize'] = 256
params['tensorboard_log_dir'] = 'logs'
### Name of output checkpoint directory

network_training.run(params)

print("Done")


description    : norm_std
datafile       : Data/snail_images.npy
labelsfile     : Data/snail_labels.npy
CheckpointDir  : Checkpoints/test
num_channels   : 5
channels       : [0, 2, 4]
combine        : [[0, 8], [4, 7]]
clusterlist    : [0, 1, 2, 3, 4, 5, 6]
iterations     : 25000
learning_rate  : 0.001
droprate       : 0.0
l2f            : 0.006
batchsize      : 256
tensorboard_log_dir: logs
Data/snail_images.npy
(35469, 7) [0 0 0 ... 4 4 4]
(35469, 7)
reducing classes
[[[3966.8784 3833.0723 6992.8394]]] -13.829564 25.962786
Done normalzing
ok to train
couldn't delete tensorboard logs


The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
Use `tf.keras.la

14000 1.1180501 1.1397066 0.0003966778064220254
15000 1.0271515 1.116511 0.0003966778064220254
16000 1.0136986 1.0903158 0.0003966778064220254
17000 1.131758 1.1050518 0.0003966778064220254
18000 1.1108134 1.0840458 0.0003966778064220254
19000 1.1230026 1.0897068 0.0003966778064220254
20000 1.0853842 1.157664 0.0003966778064220254
!!! Best accuracy:  20500 0.70703125 0.9873811
21000 1.0444198 1.0579578 0.0003966778064220254
22000 0.99729085 1.0463607 0.0003966778064220254
23000 0.9054307 1.1347591 0.0003966778064220254
24000 1.0103849 1.0670905 0.0003966778064220254
[[369   9  38  48   3  25  19]
 [  0  37   1   7   3   3   2]
 [  7   2  34   5   1   2   0]
 [  5  11   3 129   1   3   4]
 [  1   1   0   0  28   3   1]
 [  5   5   0   2  16  53   6]
 [  5   5   2  11  12  12  43]]
              precision    recall  f1-score   support

           0       0.93      0.78      0.85      1889
           1       0.38      0.55      0.45       152
           2       0.49      0.63      0.55   